# Generated by Django 3.1.7 on 2021-07-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creationdate',
            new_name='creation_date',
        ),
    ]
