# Generated by Django 4.1.5 on 2023-04-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0007_hashtag_meep_content_alter_meep_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='content',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='hashtags',
        ),
    ]
