# Generated by Django 4.1.5 on 2023-04-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0008_remove_meep_content_remove_meep_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='name',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(default='default_tag', max_length=100),
        ),
        migrations.AddField(
            model_name='meep',
            name='hashtags',
            field=models.ManyToManyField(related_name='meeps', to='ransom.hashtag'),
        ),
        migrations.AddField(
            model_name='meep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
