# Generated by Django 4.1.5 on 2023-04-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0009_remove_hashtag_name_hashtag_tag_meep_hashtags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
