# Generated by Django 4.1.5 on 2023-04-02 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ransom', '0010_remove_meep_hashtags_remove_meep_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
