# Generated by Django 4.1.5 on 2023-04-02 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ransom', '0011_meep_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='meep',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeps', to=settings.AUTH_USER_MODEL),
        ),
    ]
