# Generated by Django 4.1.5 on 2023-04-02 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ransom', '0012_remove_meep_last_modified_alter_meep_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_meeps', to=settings.AUTH_USER_MODEL),
        ),
    ]
